#! /bin/sh

# Encoder settings.
/usr/bin/v4l2-ctl --set-ctrl=h264_profile=1
/usr/bin/v4l2-ctl --set-ctrl=h264_level=9
/usr/bin/v4l2-ctl --set-ctrl=video_bitrate=1500000

# HTTPS and WSS server.
/usr/bin/node /srv/zerowrtc/server.js 

# Sleep
sleep 10

# WebRTC GStreamer client.
/usr/bin/python3 /srv/zerowrtc/client.py
